spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-02.cleardb.com:3306/heroku_a3f774e3ab98d63?reconnect=true
    username: b38460ee854098
    password: 5e57638c
    hikari:
      max-lifetime: 600000

server:
  port: 9000
